---
include:
  - project: ${AC_CICD_TEMPLATES}
    file: ['code-quality.yml']
    ref: 'v0.3.1'

stages:
  - code_quality
  - mirror

variables:
  SONARQUBE_DISABLED: 'true'
  PYTEST_UNIT_TESTS_DISABLED: 'true'
  PYTEST_INTEGRITY_TESTS_DISABLED: 'true'

mirror:
  stage: mirror
  parallel:
    matrix:
      - IMAGE_NAME:
          - "cpu.core"
          - "cpu.ffmpeg"
          - "cpu.base"
          - "gpu.core"
          - "gpu.ffmpeg"
          - "gpu.base"
          - "gpu.pytorch"
          - "gpu.video"
          - "gpu.core.opt"
          - "gpu.ffmpeg.opt"
          - "gpu.base.opt"
          - "gpu.pytorch.opt"
          - "gpu.video.opt"
          - "cpu.core.rootless"
          - "cpu.ffmpeg.rootless"
          - "cpu.base.rootless"
          - "gpu.core.rootless"
          - "gpu.ffmpeg.rootless"
          - "gpu.base.rootless"
          - "gpu.pytorch.rootless"
          - "gpu.video.rootless"
          - "gpu.core.opt.rootless"
          - "gpu.ffmpeg.opt.rootless"
          - "gpu.base.opt.rootless"
          - "gpu.pytorch.opt.rootless"
          - "gpu.video.opt.rootless"
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    VERSION: "24.06"
  script:
    - crane auth login
      -u ${CI_REGISTRY_USER}
      -p ${CI_REGISTRY_PASSWORD}
      ${CI_REGISTRY}
    - crane cp
      ghcr.io/osai-ai/dokai:${VERSION}-${IMAGE_NAME}
      ${CI_REGISTRY_IMAGE}/dokai:${VERSION}-${IMAGE_NAME}
  only:
    refs:
      - tags
