---
include:
  - project: ${AC_CICD_TEMPLATES}
    file: ['code-quality.yml']
    ref: 'v0.4.3'

stages:
  - code_quality
  - mirror

variables:
  SONARQUBE_DISABLED: 'true'
  PYTEST_UNIT_TESTS_DISABLED: 'true'
  PYTEST_INTEGRITY_TESTS_DISABLED: 'true'

mirror:
  stage: mirror
  parallel:
    matrix:
      - IMAGE_NAME:
          - "cpu.pytorch"
          - "cpu.pytorch.rootless"
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    VERSION: "24.06"
  script:
    - crane auth login
      -u ${CI_REGISTRY_USER}
      -p ${CI_REGISTRY_PASSWORD}
      ${CI_REGISTRY}
    - crane cp
      ghcr.io/osai-ai/dokai:${VERSION}-${IMAGE_NAME}
      ${CI_REGISTRY_IMAGE}/dokai:${VERSION}-${IMAGE_NAME}
  only:
    refs:
      - branches
