FROM dokai:pytorch

# Install TensorStream
RUN git clone --depth=1 --branch=0.5.0 --single-branch https://github.com/osai-ai/tensor-stream.git && \
    cd tensor-stream && \
    pip3 install . && \
    cd .. && rm -rf tensor-stream
