FROM dokai:pytorch

# Install TensorStream
RUN git clone --depth 1 -b dev --single-branch https://github.com/osai-ai/tensor-stream.git &&\
    cd tensor-stream &&\
    TORCH_CUDA_ARCH_LIST="6.0;6.1;7.0;7.5;8.0;8.6" python setup.py install &&\
    cd .. && rm -rf tensor-stream
