FROM dokai:pytorch

# Install TensorStream
RUN git clone --depth=1 --branch=ffmpeg_6.0 --single-branch https://github.com/osai-ai/tensor-stream.git && \
    cd tensor-stream && \
    python setup.py install && \
    cd .. && rm -rf tensor-stream
