FROM dokai:cpu.ffmpeg.rootless

USER root

# Install libraries requirements
COPY requirements/apt/xwindow.txt xwindow.txt
RUN apt-get update && apt -y upgrade && \
    xargs apt-get -y install < xwindow.txt && \
    rm xwindow.txt && \
    apt-get clean && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/*

USER $UNAME

# Install Python packages
COPY requirements/pip/base.txt base.txt
RUN pip3 install --no-cache-dir --user -r base.txt
